language: python
python:
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: "python manage.py test"

# command to run coverage
script: "python manage.py cov"

codecov
CODECOV_TOKEN="d7f97bf6-f71f-4e38-b100-d96fcf749d59"

[testenv]
passenv =
  CI
  TRAVIS
  TRAVIS_*
